### ISSUE TITLE
[BUG] "panic: assignment to entry in nil map" when using param_groups in v1.16.x

### ISSUE THREAD

**Issue by PhantomPhreak** [ContentSquare/chproxy#188]
Trying to run v1.15.1 and v1.16.0 with a following simple config
```
---
log_debug: false
hack_me_please: true

param_groups:
- name: test_params
  params:
    - key: "aa"
      value: "11"
  
users:
- name: test_user
  password: test_password
  to_cluster: test_cluster
  to_user: test_cluster_user
  params: test_params

clusters:
- name: test_cluster
  scheme: http
  nodes:
  - test.host:8123
  users:
  - name: test_cluster_user
    password: test_cluster_user_password

server:
  http:
    listen_addr: :8088
```
v1.15.1 works fine
```
[root@host:~/src/chproxy]# git checkout tags/v1.15.1
Previous HEAD position was a5f1614 doc(max_exec_time): set by default to 30s (#186)
HEAD is now at 0468f31 fix sessionTimeout passed as a query param
[root@host:~/src/chproxy]# make build
go build
[root@host:~/src/chproxy]# ./chproxy -config /tmp/chproxy-conf.yaml
INFO: 2022/07/14 04:51:05 main.go:46: chproxy ver. unknown, rev. unknown, built at unknown
INFO: 2022/07/14 04:51:05 main.go:47: Loading config: /tmp/chproxy-conf.yaml
INFO: 2022/07/14 04:51:05 main.go:280: Loaded config:
server:
  http:
    listen_addr: :8088
    forceautocerthandler: false
    read_timeout: 1m
    write_timeout: 90s
    idle_timeout: 10m
clusters:
- name: test_cluster
  scheme: http
  nodes:
  - test.host:8123
  users:
  - name: test_cluster_user
    password: XXX
  heartbeat:
    interval: 5s
    timeout: 3s
    request: /?query=SELECT%201
    response: |
      1
users:
- name: test_user
  password: XXX
  to_cluster: test_cluster
  to_user: test_cluster_user
  max_execution_time: 30s
  params: test_params
hack_me_please: true
param_groups:
- name: test_params
  params:
  - key: aa
    value: "11"
INFO: 2022/07/14 04:51:05 main.go:55: Loading config "/tmp/chproxy-conf.yaml": successful
INFO: 2022/07/14 04:51:05 main.go:160: Serving http on ":8088"
ERROR: 2022/07/14 04:51:05 scope.go:657: error while health-checking "test.host:8123" host: cannot send request in 108.529709ms: Get "http://test.host:8123/?query=SELECT%201": dial tcp: lookup test.host: no such host
^C
```

v1.16.0 (and recent versions) throwing an error:
```
[root@host:~/src/chproxy]# git checkout tags/v1.16.0
Previous HEAD position was 0468f31 fix sessionTimeout passed as a query param
HEAD is now at c4aece8 Issue-128 | Allow param_ in query parameters (#175)
[root@host:~/src/chproxy]# make build
go build
[root@host:~/src/chproxy]# ./chproxy -config /tmp/chproxy-conf.yaml
INFO: 2022/07/14 04:53:51 main.go:46: chproxy ver. unknown, rev. unknown, built at unknown
INFO: 2022/07/14 04:53:51 main.go:47: Loading config: /tmp/chproxy-conf.yaml
panic: assignment to entry in nil map

goroutine 1 [running]:
main.newParamsRegistry({0xc000220340, 0x1, 0x1})
        /root/src/chproxy/scope.go:438 +0x9c
main.(*reverseProxy).applyConfig(0xc0002000c0, 0xc000224200)
        /root/src/chproxy/proxy.go:431 +0xa50
main.applyConfig(0xc000224200)
        /root/src/chproxy/main.go:273 +0x2f
main.main()
        /root/src/chproxy/main.go:52 +0x365
[root@host:~/src/chproxy]# go version
go version go1.18.4 linux/amd64
```

Just disabling `param_groups` in config make it working.
I suspect this issue may be caused by https://github.com/ContentSquare/chproxy/pull/175

**Comment by gontarzpawel** [comment]
Hello @PhantomPhreak , indeed a bug was introduced with that commit. The map isn't correctly initialised https://github.com/ContentSquare/chproxy/pull/175/files#diff-cdf1ba9d2aff2ab4ffd551b3b586b0220ffa76efe95e4926054f8abfcb50ed5cR436 

Thanks for submitting this bug report 🙏

**Comment by gontarzpawel** [comment]
Hi @PhantomPhreak , we're closing this issue. The fix has been merged, it'll be included in the next release

**Comment by PhantomPhreak** [comment]
@Garnek20 
Just tested, everything seem working fine now. Many thanks for the quick response :pray:
